---
- name: Configure Nginx Web Server and Deploy Sample Page
  hosts: all
  become: yes # Use 'sudo' for all tasks

  tasks:
    # This task prevents connection errors by waiting for the server to be ready.
    - name: Wait for SSH to become available
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 300
        state: started

    # This ensures the package manager has the latest list of available software.
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Update only if cache is older than 1 hour

    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    # This task prevents the "Destination directory does not exist" error.
    - name: Create Nginx web root directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Create a sample index.html page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Provisioned by Terraform + Ansible</h1>"

    - name: Ensure nginx service is started and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes