---
- name: Configure EC2 instance (Ubuntu)
  hosts: all
  become: yes
  vars:
    docker_pkg: docker.io

  tasks:
    - name: Wait for SSH up (retry until connect)
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 300
        state: started

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - "{{ docker_pkg }}"
        state: present
        update_cache: yes

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create a sample index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Provisioned by Terraform + Ansible</h1>"

    - name: Ensure nginx installed
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Verify nginx is running
      uri:
        url: "http://{{ inventory_hostname }}"
        return_content: no
        status_code: 200
      register: nginx_check
      retries: 5
      delay: 5
      until: nginx_check.status == 200
